# Generated by Django 3.2.6 on 2022-10-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
                ('number', models.PositiveIntegerField(null=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linefunc.user')),
            ],
        ),
    ]
