# Generated by Django 3.2.6 on 2022-10-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0002_store_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_food',
            name='end',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
