# Generated by Django 3.2.6 on 2022-10-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0003_store_food_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_food',
            old_name='end',
            new_name='online',
        ),
    ]
