# Generated by Django 3.2.6 on 2022-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0004_rename_end_store_food_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
