# Generated by Django 3.2.6 on 2022-10-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0008_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
