# Generated by Django 3.2.6 on 2022-11-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0009_store_food_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
