# Generated by Django 3.2.6 on 2022-11-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0010_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_now',
            field=models.BooleanField(default=True),
        ),
    ]
