# Generated by Django 3.2.6 on 2022-12-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0013_auto_20221205_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('bread', 'bread'), ('bento', 'bento')], default='bread', max_length=255),
        ),
    ]
