# Generated by Django 3.2.6 on 2022-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0016_alter_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('bread', '麵包'), ('bento', '便當')], default='bread', max_length=255),
        ),
    ]
