# Generated by Django 3.2.6 on 2022-12-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0017_alter_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_food',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
