# Generated by Django 3.2.6 on 2022-12-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0019_alter_store_food_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_food',
            name='end_get_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='store_food',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
