# Generated by Django 3.2.6 on 2022-12-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0020_auto_20221208_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_food',
            old_name='end_time',
            new_name='end_order_time',
        ),
    ]
