# Generated by Django 3.2.6 on 2022-12-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0022_rename_time_order_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
