# Generated by Django 3.2.6 on 2022-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0026_order_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='certificate',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
