# Generated by Django 3.2.6 on 2022-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0027_order_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='certificate',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='check',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_get',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_now',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
