# Generated by Django 3.2.6 on 2022-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0029_alter_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
