# Generated by Django 3.2.6 on 2022-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefunc', '0030_alter_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.ManyToManyField(to='linefunc.Store'),
        ),
    ]
